-- SQL SCHEMA FOR YUSUF RAMADANI PORTFOLIO (SUPABASE)
-- Last Updated: Jan 16, 2026

-- ==========================================
-- 1. TABLES SETUP
-- ==========================================

-- PROJECTS TABLE
create table if not exists projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  category text,
  description text,
  tech text[], -- Array of strings for tech stack
  image text default 'https://via.placeholder.com/800x600/0a0a0a/3b82f6?text=Project+Preview',
  color text default 'from-blue-600/20 to-cyan-600/20',
  demo_link text,
  repo_link text
);

-- SKILLS TABLE
create table if not exists skills (
  id bigint generated by default as identity primary key,
  name text not null,
  level integer check (level >= 0 and level <= 100),
  color text default '#3b82f6'
);

-- EDUCATION TABLE
create table if not exists education (
  id bigint generated by default as identity primary key,
  year text,
  title text,
  institution text,
  description text
);

-- ==========================================
-- 2. ENABLE ROW LEVEL SECURITY (RLS)
-- ==========================================
-- By default, Supabase blocks all access. 
-- We want anyone to be able to READ data, but only you (authenticated) to WRITE.

alter table projects enable row level security;
alter table skills enable row level security;
alter table education enable row level security;

-- Create Policies for Public Read Access
create policy "Allow public read-only access on projects" on projects for select using (true);
create policy "Allow public read-only access on skills" on skills for select using (true);
create policy "Allow public read-only access on education" on education for select using (true);

-- ==========================================
-- 3. SEED DATA (SAMPLE)
-- ==========================================

insert into projects (title, category, description, tech, color, demo_link, repo_link) values
('Nebula Dashboard', 'Fullstack App', 'A futuristic data visualization dashboard with real-time analytics and glassmorphism UI.', ARRAY['React', 'D3.js', 'Supabase'], 'from-blue-600/20 to-cyan-600/20', '#', '#'),
('Cyber Commerce', 'E-commerce', 'High-performance online store with 3D product previews and seamless checkout flow.', ARRAY['Next.js', 'Three.js', 'Stripe'], 'from-purple-600/20 to-pink-600/20', '#', '#'),
('Void Chat', 'Real-time App', 'Encrypted messaging platform with custom-built sockets and a sleek dark interface.', ARRAY['Node.js', 'Socket.io', 'Tailwind'], 'from-green-600/20 to-emerald-600/20', '#', '#');

insert into skills (name, level, color) values
('React', 90, '#61DAFB'),
('Node.js', 85, '#339933'),
('Tailwind', 95, '#06B6D4'),
('TypeScript', 80, '#3178C6');

insert into education (year, title, institution, description) values
('2020 - 2024', 'Bachelor of Computer Science', 'University of Technology', 'Specialized in Software Engineering and Web Technologies.'),
('2018 - 2020', 'Frontend Certification', 'Tech Academy', 'Comprehensive study of modern frontend frameworks and UI/UX design.');



